<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;
use Illuminate\Support\Facades\Log;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            ['name' => 'Ultrasound', 'price' => 3000],
            ['name' => 'Echo', 'price' => 3500],
            ['name' => 'Albumin', 'price' => 500],
            ['name' => 'ALT (SGPT)', 'price' => 570],
            ['name' => 'AST (SGOT)', 'price' => 700],
            ['name' => 'Serum Amylase', 'price' => 1500],
            ['name' => 'ANA', 'price' => 2700],
            ['name' => 'Anti CCP', 'price' => 3500],
            ['name' => 'Anti Mullerian Hormone', 'price' => 5200],
            ['name' => 'ASO', 'price' => 1500],
            ['name' => 'B12 Level', 'price' => 2500],
            ['name' => 'Beta HCG', 'price' => 2200],
            ['name' => 'Total Bilirubin', 'price' => 1400],
            ['name' => 'Direct Bilirubin', 'price' => 700],
            ['name' => 'Indirect Bilirubin', 'price' => 700],
            ['name' => 'Blood C/S', 'price' => 2500],
            ['name' => 'Blood Grouping', 'price' => 500],
            ['name' => 'Blood Urea', 'price' => 700],
            ['name' => 'BSF', 'price' => 350],
            ['name' => 'BSR', 'price' => 350],
            ['name' => 'BT, CT', 'price' => 700],
            ['name' => 'CA 125', 'price' => 4000],
            ['name' => 'Calcium', 'price' => 700],
            ['name' => 'Chem 7', 'price' => 3700],
            ['name' => 'C Peptide', 'price' => 4200],
            ['name' => 'Covid 19 Antibodies by ELISA', 'price' => 4500],
            ['name' => 'Covid 19 Rapid Antigen', 'price' => 3000],
            ['name' => 'Covid 19 PCR', 'price' => 5000],
            ['name' => 'Covid 19 IgG, IgM', 'price' => 4000],
            ['name' => 'Covid 19 Spike Ab', 'price' => 3000],
            ['name' => 'Complete Blood Picture', 'price' => 1000],
            ['name' => 'CP - ESR', 'price' => 1200],
            ['name' => 'CPK', 'price' => 800],
            ['name' => 'Creatinine', 'price' => 700],
            ['name' => 'CRP Quantitative', 'price' => 1500],
            ['name' => 'Culture Bottle', 'price' => 800],
            ['name' => 'D-Dimer', 'price' => 2200],
            ['name' => 'Dengue ELISA IgG', 'price' => 2500],
            ['name' => 'Dengue ELISA IgM', 'price' => 2500],
            ['name' => 'Dengue NS1', 'price' => 2000],
            ['name' => 'Dengue NS1 by ELISA', 'price' => 2600],
            ['name' => 'Dengue Profile', 'price' => 5000],
            ['name' => 'Dengue Virus Screening IgG, IgM', 'price' => 2000],
            ['name' => 'Dental Implant', 'price' => 100000],
            ['name' => 'DOPE Test', 'price' => 4000],
            ['name' => 'Dressing', 'price' => 500],
            ['name' => 'Drug of Abuse Profile Urine', 'price' => 5800],
            ['name' => 'Electrolytes', 'price' => 1700],
            ['name' => 'ESR', 'price' => 300],
            ['name' => 'Estradiol', 'price' => 2000],
            ['name' => 'Estrogen', 'price' => 2000],
            ['name' => 'Ferritin', 'price' => 2000],
            ['name' => 'Fluid for C/S', 'price' => 2000],
            ['name' => 'Fluid R/E', 'price' => 2000],
            ['name' => 'FNAC', 'price' => 5000],
            ['name' => 'Folic Acid', 'price' => 1800],
            ['name' => 'Free T3', 'price' => 2200],
            ['name' => 'Free T4', 'price' => 2200],
            ['name' => 'FSH', 'price' => 2000],
            ['name' => 'Fungus Culture', 'price' => 2000],
            ['name' => 'G6PD Screening Test', 'price' => 2300],
            ['name' => 'Glucose Fasting', 'price' => 400],
            ['name' => 'Glucose Random', 'price' => 400],
            ['name' => 'Glucose Challenge Test', 'price' => 1500],
            ['name' => 'Glucose Tolerance Test', 'price' => 1700],
            ['name' => 'Gram Stain', 'price' => 600],
            ['name' => 'Growth Hormone', 'price' => 3200],
            ['name' => 'H. Pylori ELISA IgG', 'price' => 2400],
            ['name' => 'H. Pylori ELISA IgM', 'price' => 2800],
            ['name' => 'H. Pylori Antibody', 'price' => 1500],
            ['name' => 'H. Pylori Stool Antigen', 'price' => 3800],
            ['name' => 'Hb Electrophoresis', 'price' => 3200],
            ['name' => 'HbA1C', 'price' => 1800],
            ['name' => 'Hbs A Screening', 'price' => 1000],
            ['name' => 'HbsAg ELISA', 'price' => 1700],
            ['name' => 'HbsAg Screening', 'price' => 850],
            ['name' => 'HCV PCR Qualitative', 'price' => 7000],
            ['name' => 'HCV PCR Quantitative', 'price' => 12000],
            ['name' => 'HDL Cholesterol', 'price' => 700],
            ['name' => 'Hep B PCR Qualitative', 'price' => 8000],
            ['name' => 'Hep B PCR Quantitative', 'price' => 12000],
            ['name' => 'Histopathology Large', 'price' => 5500],
            ['name' => 'Histopathology Medium', 'price' => 4500],
            ['name' => 'Histopathology Small', 'price' => 3700],
            ['name' => 'HIV 1 & 2 Ab ELISA', 'price' => 2500],
            ['name' => 'HIV Screening', 'price' => 1500],
            ['name' => 'HVS Culture', 'price' => 2500],
            ['name' => 'ICT - MP', 'price' => 1300],
            ['name' => 'ICT - TB / Mycodot', 'price' => 1300],
            ['name' => 'Immunoglobulin E (IgE)', 'price' => 1700],
            ['name' => 'Insulin Level', 'price' => 1500],
            ['name' => 'Insulin Level 2 hour PP', 'price' => 3500],
            ['name' => 'Insulin Level Fasting', 'price' => 3500],
            ['name' => 'Iron', 'price' => 900],
            ['name' => 'Iron + TIBC', 'price' => 2000],
            ['name' => 'LDH', 'price' => 800],
            ['name' => 'LDL Cholesterol', 'price' => 1500],
            ['name' => 'LH', 'price' => 2000],
            ['name' => 'Lipase', 'price' => 1500],
            ['name' => 'Lipid Profile', 'price' => 2000],
            ['name' => 'Liver Function Tests', 'price' => 1700],
            ['name' => 'Montoux Test', 'price' => 700],
            ['name' => 'Malarial Parasite Smear', 'price' => 800],
            ['name' => 'Mycodot', 'price' => 1500],
            ['name' => 'Pap Smear', 'price' => 3000],
            ['name' => 'Parathyroid Hormone', 'price' => 4000],
            ['name' => 'Peripheral Blood Film', 'price' => 1200],
            ['name' => 'Pregnancy Test', 'price' => 500],
            ['name' => 'Prolactin', 'price' => 2200],
            ['name' => 'PSA', 'price' => 3000],
            ['name' => 'PT & APTT', 'price' => 1800],
            ['name' => 'PT', 'price' => 1000],
            ['name' => 'Pus Culture', 'price' => 2000],
            ['name' => 'RA Factor', 'price' => 1000],
            ['name' => 'RA Factor Quantitative', 'price' => 2500],
            ['name' => 'Renal Function Tests', 'price' => 1800],
            ['name' => 'Semen Analysis', 'price' => 1500],
            ['name' => 'Sex Hormone Binding Globulin', 'price' => 4500],
            ['name' => 'Sodium', 'price' => 900],
            ['name' => 'Sputum for AFB', 'price' => 600],
            ['name' => 'Syphilis by ELISA', 'price' => 2500],
            ['name' => 'TPHA', 'price' => 2600],
            ['name' => 'Stool for Occult Blood', 'price' => 1000],
            ['name' => 'Sputum for Culture', 'price' => 2000],
            ['name' => 'Sputum R/E', 'price' => 1500],
            ['name' => 'Stool C/S', 'price' => 2000],
            ['name' => 'Stool for H. Pylori', 'price' => 4000],
            ['name' => 'Stool R/E', 'price' => 700],
            ['name' => 'T3', 'price' => 1500],
            ['name' => 'T4', 'price' => 1500],
            ['name' => 'TB by ELISA (IgG, IgM)', 'price' => 2200],
            ['name' => 'TB GOLD', 'price' => 15000],
            ['name' => 'Testosterone', 'price' => 2000],
            ['name' => 'Thyroid Profile', 'price' => 3800],
            ['name' => 'Anti Thyroglobulin', 'price' => 2200],
            ['name' => 'TSH Receptor Antibody', 'price' => 5000],
            ['name' => 'Anti TPO', 'price' => 3000],
            ['name' => 'Triglycerides', 'price' => 700],
            ['name' => 'TSH', 'price' => 1500],
            ['name' => 'Typhidot (IgM)', 'price' => 1200],
            ['name' => 'Typhidot (IgG & IgM)', 'price' => 1200],
            ['name' => 'Ultrasound Guided Biopsy', 'price' => 19800],
            ['name' => 'Urea', 'price' => 1000],
            ['name' => 'Urea & Creatinine', 'price' => 1000],
            ['name' => 'Uric Acid', 'price' => 650],
            ['name' => 'Urinary Albumin', 'price' => 500],
            ['name' => 'Urinary Amylase', 'price' => 900],
            ['name' => 'Urine C/S', 'price' => 2500],
            ['name' => 'Urine for Bile Salt', 'price' => 600],
            ['name' => 'Urine for TLC', 'price' => 800],
            ['name' => 'Urine for 10 Drugs', 'price' => 5800],
            ['name' => 'Urine R/E', 'price' => 500],
            ['name' => 'Vitamin B12', 'price' => 2500],
            ['name' => 'Vitamin D3', 'price' => 3500],
            ['name' => 'Widal Test', 'price' => 900],
            ['name' => 'Serum Zinc', 'price' => 4100],
            ['name' => 'VDRL', 'price' => 1200],
        ];

        foreach ($services as $service) {
            try {
                Service::firstOrCreate(
                    ['name' => $service['name']],  // check unique by name
                    ['price' => $service['price']]
                );
            } catch (\Exception $e) {
                Log::error("Failed to insert service: {$service['name']}, Error: {$e->getMessage()}");
            }
        }
    }
}
